# Generated by Django 3.0.8 on 2020-08-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_card_text', models.CharField(help_text='content of the front of the card', max_length=200)),
                ('back_card_text', models.CharField(help_text='content of the back of the card', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer is correct or not')),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash_card_app.FlashCard')),
            ],
        ),
    ]
